spring:
  datasource:
    username: root
    password: 12344
    url: jdbc:mysql://localhost:3306/calligraphy_boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true

